import piexif from "piexifjs";
import { strFromBytes } from "./exif";
const P:any=piexif as any;
export type FindingStatus="found"|"warn"|"clean";
export interface Finding{id:string;label:string;status:FindingStatus;detail:string;}
export interface AuditResult{fileType:string;fileSize:number;c2pa:boolean;xmp:boolean;creatorTool:string;generatorHits:string[];exifMake:string;exifModel:string;exifSoftware:string;findings:Finding[];}
const markers=["midjourney","dall-e","dalle","stable diffusion","sdxl","firefly","generative ai","imagen","leonardo","ideogram","flux","dreamstudio","clipdrop","runway","pika","sora"];
function typeOf(b:Uint8Array){if(b[0]===255&&b[1]===216)return"JPEG";if(b[0]===137&&b[1]===80)return"PNG";if(b[0]===82&&b[1]===73&&b[2]===70&&b[3]===70)return"WebP";return"Unknown";}
export async function auditFile(file:File):Promise<AuditResult>{const b=new Uint8Array(await file.arrayBuffer()),s=strFromBytes(b),fileType=typeOf(b),findings:Finding[]=[];const c2pa=s.toLowerCase().includes("c2pa")||s.includes("jumb");let xmpPacket="";const start=Math.max(s.indexOf("<?xpacket begin"),s.indexOf("<x:xmpmeta"));if(start>=0)xmpPacket=s.slice(start,Math.min(start+40000,s.length));const xmp=!!xmpPacket;const creatorTool=(/CreatorTool="([^"]*)"/.exec(xmpPacket)?.[1]||"").trim();let exifMake="",exifModel="",exifSoftware="";try{const o=P.load(s);const g=(tag:number)=>{const v=o?.["0th"]?.[tag];return typeof v==="string"?v:Array.isArray(v)?String.fromCharCode(...v):""};exifMake=g(271).trim();exifModel=g(272).trim();exifSoftware=g(305).trim();}catch{}const hits=markers.filter(m=>(xmpPacket+" "+exifSoftware).toLowerCase().includes(m));findings.push({id:"c2pa",label:"C2PA / Content Credentials",status:c2pa?"found":"clean",detail:c2pa?"A provenance marker appears to be present.":"No C2PA marker detected."});findings.push({id:"xmp",label:"XMP metadata",status:xmp?(hits.length?"found":"warn"):"clean",detail:xmp?`XMP present${creatorTool?` · ${creatorTool}`:""}`:"No XMP packet detected."});findings.push({id:"gen",label:"Generator markers",status:hits.length?"found":"clean",detail:hits.length?hits.join(", "):"No common generator markers found."});findings.push({id:"exif",label:"Camera EXIF",status:exifMake||exifModel?"found":"clean",detail:`${exifMake||"—"} ${exifModel||""}${exifSoftware?` · ${exifSoftware}`:""}`});return{fileType,fileSize:file.size,c2pa,xmp,creatorTool,generatorHits:hits,exifMake,exifModel,exifSoftware,findings};}
