import piexif from "piexifjs";
import type { MetaFields } from "../types";
const P: any = (piexif as any) ?? window;
type Ifd = Record<string, unknown>;
export const strFromBytes=(bytes:Uint8Array):string=>{let s="";const chunk=8192;for(let i=0;i<bytes.length;i+=chunk)s+=String.fromCharCode(...bytes.subarray(i,i+chunk));return s;};
const binaryStrToUint8=(str:string):Uint8Array=>{const a=new Uint8Array(str.length);for(let i=0;i<str.length;i++)a[i]=str.charCodeAt(i)&0xff;return a;};
const pad2=(n:number)=>String(n).padStart(2,"0");
const toRational=(val:number):[number,number]=>{if(!isFinite(val)||val===0)return[0,1];if(val<0.1)return[1,Math.round(1/val)];const scale=1000;return[Math.round(val*scale),scale];};
const isoForCamera=(iso:number):number=>({3200:320,6400:640,12800:1280}[iso]??iso);
const trimNum=(n:number)=>n.toFixed(4).replace(/\.?0+$/ ,"");
const ascii=(str:string):number[]=>[...str].map(c=>c.charCodeAt(0)&0xff);
export interface ReadResult{fields:MetaFields;exifFound:boolean;exifSummary:string[];imgWidth:number;imgHeight:number;}
export async function readMetadata(file:File):Promise<ReadResult>{
 const bytes=new Uint8Array(await file.arrayBuffer());
 const img=await createImageBitmap(new Blob([bytes.buffer as ArrayBuffer],{type:"application/octet-stream"}));
 const w=img.width,h=img.height;img.close();const summary:string[]=[`Image: ${w} × ${h} px`];let exifFound=false,exifObj:any=null;
 try{exifObj=P.load(strFromBytes(bytes));exifFound=!!exifObj&&!!(exifObj["0th"]||exifObj.Exif||exifObj.GPS);}catch{exifFound=false;}
 const fields=defaultFields();
 if(exifFound&&exifObj){summary.push("Existing EXIF found — values pre-filled below.");const getStr=(ifd:string,tag:number):string=>{const v=exifObj[ifd]?.[tag];if(typeof v==="string")return v;if(Array.isArray(v))return String.fromCharCode(...v.map((x:number)=>x&0xff));return"";};const getNum=(ifd:string,tag:number):number|undefined=>{const v=exifObj[ifd]?.[tag];if(typeof v==="number")return v;if(Array.isArray(v)&&v.length&&Array.isArray(v[0]))return v[0][0]/(v[0][1]||1);if(Array.isArray(v)&&v.length)return v[0];return undefined;};
 const make=getStr("0th",271).trim(),model=getStr("0th",272).trim(),sw=getStr("0th",305).trim(),dt=getStr("Exif",36867)||getStr("0th",306),lm=getStr("Exif",42036).trim(),cv=getStr("0th",33432).trim(),ar=getStr("0th",315).trim();
 if(make)fields.make=make;if(model)fields.model=model;if(sw)fields.software=sw;if(dt)fields.dateTime=dt;if(lm)fields.lens=lm;if(cv)fields.copyright=cv;if(ar)fields.artist=ar;if(make)summary.push(`Camera: ${make} ${model}`.trim());if(dt)summary.push(`Original timestamp: ${dt}`);
 const isoV=getNum("Exif",34855);if(isoV){fields.iso=isoV;summary.push(`ISO: ${isoV}`);}const et=getNum("Exif",33434);if(et)fields.shutter=trimNum(et);const fn=getNum("Exif",33437);if(fn)fields.aperture=trimNum(fn);const fl=getNum("Exif",37386);if(fl)fields.focalLength=trimNum(fl);const f35=getNum("Exif",41989);if(f35)fields.focal35mm=f35;const ep=getNum("Exif",34850);if(ep!==undefined)fields.exposureProgram=ep;const mm=getNum("Exif",37383);if(mm!==undefined)fields.meteringMode=mm;const ls=getNum("Exif",37384);if(ls!==undefined)fields.lightSource=ls;const wb=getNum("Exif",41987);if(wb!==undefined)fields.whiteBalance=wb;const sd=getNum("Exif",41996);if(sd!==undefined)fields.subjectDistanceRange=sd;
 const glat=exifObj.GPS?.[2],glon=exifObj.GPS?.[4];if(glat&&glon)try{fields.gpsLat=trimNum(P.GPSHelper.dmsRationalToDeg(glat,getStr("GPS",1)));fields.gpsLon=trimNum(P.GPSHelper.dmsRationalToDeg(glon,getStr("GPS",3)));fields.gpsInclude=true;summary.push(`GPS: ${fields.gpsLat}, ${fields.gpsLon}`);}catch{}
 if(!make&&!model&&!dt)summary.push("EXIF block present but no recognizable camera tags.");
 }else summary.push("No EXIF data found in this file.");return{fields,exifFound,exifSummary:summary,imgWidth:w,imgHeight:h};
}
const defaultFields=():MetaFields=>{const now=new Date();return{make:"Apple",model:"iPhone 15 Pro",lens:"",software:"17.4",dateTime:`${now.getFullYear()}:${pad2(now.getMonth()+1)}:${pad2(now.getDate())} ${pad2(now.getHours())}:${pad2(now.getMinutes())}:${pad2(now.getSeconds())}`,exposureProgram:1,iso:100,shutter:"0.016",aperture:"2.8",focalLength:"50",bias:0,meteringMode:2,lightSource:0,flash:false,whiteBalance:0,focal35mm:0,subjectDistanceRange:0,copyright:"",artist:"",gpsLat:"",gpsLon:"",gpsAlt:"0",gpsInclude:false};};
export async function writeExif(file:File,fields:MetaFields,quality:number):Promise<{blob:Blob;metaSize:number}>{
 const bytes=new Uint8Array(await file.arrayBuffer());const img=await createImageBitmap(new Blob([bytes.buffer as ArrayBuffer],{type:"application/octet-stream"}));const canvas=document.createElement("canvas");canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext("2d")!;ctx.drawImage(img,0,0);img.close();
 const jpegBlob=await new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("JPEG encoding failed")),"image/jpeg",quality));const jpegBytes=new Uint8Array(await jpegBlob.arrayBuffer()),w=canvas.width,h=canvas.height;const zeroth:Ifd={},exif:Ifd={},gps:Ifd={};
 zeroth[274]=1;zeroth[256]=w;zeroth[257]=h;zeroth[271]=ascii(fields.make.trim()||"Unknown");zeroth[272]=ascii(fields.model.trim()||"Unknown");if(fields.software.trim())zeroth[305]=ascii(fields.software.trim());if(fields.artist.trim())zeroth[315]=ascii(fields.artist.trim());if(fields.copyright.trim())zeroth[33432]=ascii(fields.copyright.trim());
 const dt=fields.dateTime.trim(),validDt=/^\d{4}:\d{2}:\d{2} \d{2}:\d{2}:\d{2}$/.test(dt),dateStr=validDt?dt:"2024:01:01 12:00:00";exif[36864]=[48,53,48,48];exif[36867]=ascii(dateStr);exif[36868]=ascii(dateStr);exif[33434]=toRational(parseFloat(fields.shutter)||1/60);exif[33437]=toRational(parseFloat(fields.aperture)||2.8);exif[34850]=fields.exposureProgram;exif[34855]=isoForCamera(fields.iso);exif[37383]=fields.meteringMode;exif[37384]=fields.lightSource;exif[37385]=fields.flash?9:16;exif[37386]=toRational(parseFloat(fields.focalLength)||50);exif[41987]=fields.whiteBalance;exif[41996]=fields.subjectDistanceRange;exif[37380]=[fields.bias,1];exif[40961]=1;exif[40962]=w;exif[40963]=h;exif[40960]=[48,50,48,48];exif[41728]=[83,78,32,32];exif[41729]=1;exif[41985]=0;exif[41990]=0;exif[41991]=0;exif[41992]=0;exif[41993]=0;exif[41994]=0;if(fields.focal35mm>0)exif[41989]=fields.focal35mm;if(fields.lens.trim()){exif[42035]=ascii(fields.make.trim());exif[42036]=ascii(fields.lens.trim());}
 const lat=parseFloat(fields.gpsLat),lon=parseFloat(fields.gpsLon),hasGps=fields.gpsInclude&&fields.gpsLat.trim()!==""&&fields.gpsLon.trim()!==""&&isFinite(lat)&&isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180;if(hasGps){gps[0]=[2,3,0,0];gps[1]=ascii(lat<0?"S":"N");gps[2]=P.GPSHelper.degToDmsRational(lat);gps[3]=ascii(lon<0?"W":"E");gps[4]=P.GPSHelper.degToDmsRational(lon);const alt=parseFloat(fields.gpsAlt)||0;gps[5]=alt<0?1:0;gps[6]=[Math.abs(alt),1];const now=new Date();gps[7]=[[now.getUTCHours(),1],[now.getUTCMinutes(),1],[now.getUTCSeconds(),1]];gps[9]=ascii("A");gps[10]=ascii("3");gps[29]=ascii(`${now.getUTCFullYear()}:${pad2(now.getUTCMonth()+1)}:${pad2(now.getUTCDate())}`);gps[30]=0;}
 const exifObj:Ifd={"0th":zeroth,Exif:exif,Interop:{1:"R003"}};if(Object.keys(gps).length>0)exifObj.GPS=gps;const exifBytes=P.dump(exifObj),resultStr=P.insert(exifBytes,strFromBytes(jpegBytes)),outBytes=binaryStrToUint8(resultStr),blob=new Blob([outBytes.buffer as ArrayBuffer],{type:"image/jpeg"});return{blob,metaSize:blob.size-jpegBytes.length};
}
export function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export function formatBytes(n:number):string{if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(1)} KB`;return`${(n/(1024*1024)).toFixed(2)} MB`;}
